<?php
/**
 * Created by PhpStorm.
 * User: theodor
 * Date: 1/24/15
 * Time: 3:39 PM
 */

namespace AppBundle\Model;


class Diseases
{
    public static $diseases = [
        'Diabetes',
        'Headache',
        'Diarrhea',
        'Autism',
        'Motor neuron disease',
        'Acute disseminated encephalomyelitis',
        'Arthritis',
        'Aphasia',
        'Albinism',
        'Bipolar disorder',
        'Bacterial vaginosis',
        'Catatonia',
        'Cardiac arrhythmia',
        'Creutzfeldt–Jakob disease',
        'Chickenpox',
        'Coronary artery disease',
        'Cretinism',
        'Chagas disease',
        'Chlamydia infection',
        'Candidiasis',
        'Color blindness',
        'Cholera',
        'Cerebral arteriovenous malformation',
        'Charcot–Marie–Tooth disease',
        'DiGeorge syndrome',
        'Down syndrome',
        'Dyslexia',
        'Major depression',
        'Endocarditis',
        'Expressive aphasia',
        'Epilepsy',
        'Essential tremor',
        'Foot-and-mouth disease',
        'Goitre',
        'Guillain–Barré syndrome',
        'Hypoglycemia',
        'Hyperthyroidism',
        'Hemiparesis',
        'Erectile dysfunction',
        'Interstitial cystitis',
        'Inclusion body myositis',
        'Kwashiorkor',
        'Lassa fever',
        'Systemic lupus erythematosus',
        'Lung cancer',
        'Leukemia',
        'Lambert–Eaton myasthenic syndrome',
        'Lymphedema',
        'Muscular dystrophy',
        'Myasthenia gravis',
        'Mania',
        'Malaria',
        'Meconium aspiration syndrome',
        'Migraine',
        'Neuromyotonia',
        'Narcolepsy',
        'Nitrogen narcosis',
        'Osteoporosis',
        'Optic neuritis',
        'Phenylketonuria',
        'Pneumocystis pneumonia',
        'Psychosis',
        'Paranoia',
        'Pelvic inflammatory disease',
        'Autosomal Dominant Polycystic Kidney Disease',
        'Poliomyelitis',
        'Progressive multifocal leukoencephalopathy',
        'Idiopathic intracranial hypertension',
        'Repetitive strain injury',
        'Rheumatoid arthritis',
        'Rickets',
        'Receptive aphasia',
        'Rift Valley fever',
        'Ramsay Hunt syndrome type 2',
        'Systemic scleroderma',
        'Smallpox',
        'Schizophrenia',
        'Scurvy',
        'Stuttering',
        'Sleep apnea',
        'Sinusitis',
        'Stevens–Johnson syndrome',
        'Sickle cell disease',
        'Scabies',
        'Syphilis',
        'Serotonin syndrome',
        'Syringomyelia',
        'Tuberculosis',
        'Temporomandibular joint dysfunction',
        'Typhoid fever',
        'Giant-cell arteritis',
        'Transient ischemic attack',
        'Urethritis',
        'Urinary tract infection',
        'Vulvodynia',
        'Von Hippel–Lindau disease',
        'Varicose veins',
        'Wart',
        'Yellow fever',
        '5-alpha-reductase deficiency',
        'Cirrhosis',
        'Anorexia nervosa',
        'Brain tumor',
    ];
}